// packages/vulture/app.tsx
/*
 * @Author: sfy
 * @Date: 2022-12-07 22:06:10
 * @LastEditors: sfy
 * @LastEditTime: 2022-12-15 20:14:54
 * @FilePath: /vulture-design/packages/vulture/app.tsx
 * @Description: update here
 */
import { PublicGraph, ReactGraph } from './src/components'


export function App() {


  return (
    <>
      {/* <PublicGraph /> */}
      <ReactGraph />
    </>
  )
}

// example/app.vue
<!--
 * @Author: sfy
 * @Date: 2022-12-04 21:18:00
 * @LastEditors: sfy
 * @LastEditTime: 2022-12-06 00:16:00
 * @FilePath: /vulture-design/example/app.vue
 * @Description: update here
-->
<template>
   <div>
    测试213
   </div>
   <x-greeting name="Billy Jo"></x-greeting>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import '@vuld/vulture'
</script>
<style>
</style>
