// packages/vulture/app.tsx
/*
 * @Author: sfy
 * @Date: 2022-12-07 22:06:10
 * @LastEditors: sfy
 * @LastEditTime: 2022-12-15 20:14:54
 * @FilePath: /vulture-design/packages/vulture/app.tsx
 * @Description: update here
 */
import { PublicGraph, ReactGraph } from './src/components'


export function App() {


  return (
    <>
      {/* <PublicGraph /> */}
      <ReactGraph />
    </>
  )
}

// packages/vuele/src/App.vue
<!--
 * @Author: sfy
 * @Date: 2023-03-27 22:43:04
 * @LastEditors: sfy
 * @LastEditTime: 2023-04-03 21:49:48
 * @FilePath: /vulture-design/packages/vuele/src/App.vue
 * @Description: update here
-->
<script setup lang="ts">
import Drage from './components/drage/index.vue'
import D3Demo from './components/D3Demo/test01.vue'
</script>

<template>
  <Drage />
  <!-- <D3Demo /> -->
</template>

<style scoped>

</style>
