// packages/rele/app.tsx
/*
 * @Author: sfy
 * @Date: 2023-03-27 23:07:19
 * @LastEditors: sfy
 * @LastEditTime: 2023-03-27 23:23:37
 * @FilePath: /vulture-design/packages/rele/app.tsx
 * @Description: update here
 */
/*
 * @Author: sfy
 * @Date: 2022-12-07 22:06:10
 * @LastEditors: sfy
 * @LastEditTime: 2022-12-15 20:39:39
 * @FilePath: /vulture-design/packages/vulture/app.tsx
 * @Description: update here
 */
import React from 'react'
import { ConditionTree, ReactGraph } from './src/components'

export default function App() {


  return (
    <>
      <ReactGraph />
      {/* <ConditionTree /> */}
    </>
  )
}

// packages/vuele/src/App.vue
<!--
 * @Author: sfy
 * @Date: 2023-03-27 22:43:04
 * @LastEditors: sfy
 * @LastEditTime: 2023-04-03 21:49:48
 * @FilePath: /vulture-design/packages/vuele/src/App.vue
 * @Description: update here
-->
<script setup lang="ts">
import Drage from './components/drage/index.vue'
import D3Demo from './components/D3Demo/test01.vue'
</script>

<template>
  <Drage />
  <!-- <D3Demo /> -->
</template>

<style scoped>

</style>
